// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// even_spaced_curves_impl
SEXP even_spaced_curves_impl(SEXP x_start1, SEXP y_start1, SEXP n_curves1, SEXP n_steps1, SEXP min_steps_allowed1, SEXP step_length1, SEXP d_sep1, SEXP flow_field1, SEXP flow_field_width1);
RcppExport SEXP _rlefer_even_spaced_curves_impl(SEXP x_start1SEXP, SEXP y_start1SEXP, SEXP n_curves1SEXP, SEXP n_steps1SEXP, SEXP min_steps_allowed1SEXP, SEXP step_length1SEXP, SEXP d_sep1SEXP, SEXP flow_field1SEXP, SEXP flow_field_width1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_start1(x_start1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_start1(y_start1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_curves1(n_curves1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_steps1(n_steps1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type min_steps_allowed1(min_steps_allowed1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type step_length1(step_length1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type d_sep1(d_sep1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type flow_field1(flow_field1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type flow_field_width1(flow_field_width1SEXP);
    rcpp_result_gen = Rcpp::wrap(even_spaced_curves_impl(x_start1, y_start1, n_curves1, n_steps1, min_steps_allowed1, step_length1, d_sep1, flow_field1, flow_field_width1));
    return rcpp_result_gen;
END_RCPP
}
// non_overlapping_curves_impl
DataFrame non_overlapping_curves_impl(List starting_points, int n_curves, int n_steps, int min_steps_allowed, double step_length, double d_sep, NumericMatrix flow_field, int flow_field_width);
RcppExport SEXP _rlefer_non_overlapping_curves_impl(SEXP starting_pointsSEXP, SEXP n_curvesSEXP, SEXP n_stepsSEXP, SEXP min_steps_allowedSEXP, SEXP step_lengthSEXP, SEXP d_sepSEXP, SEXP flow_fieldSEXP, SEXP flow_field_widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type starting_points(starting_pointsSEXP);
    Rcpp::traits::input_parameter< int >::type n_curves(n_curvesSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type min_steps_allowed(min_steps_allowedSEXP);
    Rcpp::traits::input_parameter< double >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type d_sep(d_sepSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type flow_field(flow_fieldSEXP);
    Rcpp::traits::input_parameter< int >::type flow_field_width(flow_field_widthSEXP);
    rcpp_result_gen = Rcpp::wrap(non_overlapping_curves_impl(starting_points, n_curves, n_steps, min_steps_allowed, step_length, d_sep, flow_field, flow_field_width));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rlefer_even_spaced_curves_impl", (DL_FUNC) &_rlefer_even_spaced_curves_impl, 9},
    {"_rlefer_non_overlapping_curves_impl", (DL_FUNC) &_rlefer_non_overlapping_curves_impl, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_rlefer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
