# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

even_spaced_curves <- function(x_start, y_start, n_curves, n_steps, min_steps_allowed, step_length, d_sep, flow_field, flow_field_width) {
    .Call(`_rlefer_even_spaced_curves`, x_start, y_start, n_curves, n_steps, min_steps_allowed, step_length, d_sep, flow_field, flow_field_width)
}

